export const predefinedCategories = [
    'Electronics',
    'Clothing',
    'Food',
    'Beverages',
    'Furniture',
    'Kitchen Appliances',
    'Home Decor',
    'Books',
    'Toys',
    'Sports Equipment',
    'Tools',
    'Gardening',
    'Automotive',
    'Health and Beauty',
    'Cleaning Supplies',
    'Office Supplies',
    'Pet Supplies',
    'Jewelry',
    'Art Supplies',
    'Music Instruments',
    'Outdoor Equipment',
    'Luggage',
    'Crafts',
    'Baby Items',
    'Medications',
    'Party Supplies',
    'Seasonal Decorations',
    'Stationery',
    'Collectibles',
    'Other'
  ];